### PR TITLE
fix: prevent terminal popup on windows

### LINKED ISSUE #250: Telemetry gathering causes obnoxious popups and cannot be disabled
**Description**

I find the fact that we have to opt *out* of having this telemetry gathered highly questionable. But honestly what I find irritating about this package is that it briefly pops up an empty shell window when it runs which obstructs the rest of my screen and steals focus. This is on Windows.

We don't use `@ibm/telemetry-js` directly, but we do use `@carbon/react` which has numerous dependencies which use `@ibm/telemetry-js`:

```
C:\Users\s100\Downloads>npm list @ibm/telemetry-js
Downloads@ C:\Users\s100\Downloads
`-- @carbon/react@1.59.0
  +-- @carbon/feature-flags@0.20.0
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/icons-react@11.43.0
  | +-- @carbon/icon-helpers@10.48.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/layout@11.22.0
  | `-- @ibm/telemetry-js@1.5.2 deduped
  +-- @carbon/styles@1.59.0
  | +-- @carbon/colors@11.22.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/grid@11.23.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/motion@11.18.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/themes@11.36.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | +-- @carbon/type@11.27.0
  | | `-- @ibm/telemetry-js@1.5.2 deduped
  | `-- @ibm/telemetry-js@1.5.2 deduped
  `-- @ibm/telemetry-js@1.5.2
```

What this means is that when I `npm install @carbon/react`, this empty shell window pops up **eleven times!** It's exceedingly annoying and blocks my workflow for 5-6 seconds.

[According to the documentation](https://github.com/ibm-telemetry/telemetry-js?tab=readme-ov-file#opting-out-of-ibm-telemetry-data-collection) we can set the environment variable `IBM_TELEMETRY_DISABLED=true` but **this doesn't work.** How do we opt out of this?

**Steps to reproduce**

On Windows:

```cmd
set IBM_TELEMETRY_DISABLED=true
npm install @carbon/react
```

Then watch.

### PR DESCRIPTION
**Pull request by jdharvey-ibm**
Fixes #250

- Earlier checking of opt-out environment variables
- Better guidance for opting out for Windows users
- Removal of background process's spawned shell window

### CODE REVIEW

File: src/main/spawn-background-process.ts [hunk 1]
```diff
@@ -8,11 +10,15 @@ async function spawnBackgroundProcess() {
...
   const { createLogFilePath } = await import('./core/log/create-log-file-path.js')
-
   const date = new Date().toISOString()
   const logFilePath = createLogFilePath(date)
+  const environment = new Environment()
+
+  if (environment.isCI === false || environment.isTelemetryEnabled === false) {
+    // Do nothing and exit quietly
+    return
+  }
```
Comment (francinelucca) [inline src/main/spawn-background-process.ts:21]: does this superseed https://github.com/ibm-telemetry/telemetry-js/blob/main/src/main/ibm-telemetry.ts#L65-L74? if so, should we remove?

**Review by francinelucca — APPROVED** [review]
